-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES BA
WHERE   TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'   
AND     B.BOOK_ID = BA.BOOK_ID 
AND     B.AUTHOR_ID = A.AUTHOR_ID 
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC