-- SELECT TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR, 
--        TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) AS MONTH, 
--        U.GENDER, 
--        COUNT(DISTINCT O.USER_ID) AS USERS
-- FROM USER_INFO U
-- JOIN ONLINE_SALE O
--   ON U.USER_ID = O.USER_ID
-- WHERE U.GENDER IS NOT NULL
-- GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), 
--          TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')), 
--          U.GENDER
-- ORDER BY 1, 2, 3;

SELECT TO_CHAR(SALES_DATE,'YYYY') YEAR, 
       TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) MONTH, 
       U.GENDER,
       COUNT(DISTINCT O.USER_ID) USERS
FROM USER_INFO U
JOIN 
    (SELECT DISTINCT USER_ID, TO_CHAR(SALES_DATE, 'YYYY-MM') ODATE, SALES_DATE
     FROM ONLINE_SALE
     GROUP BY USER_ID, TO_CHAR(SALES_DATE, 'YYYY-MM'), SALES_DATE) O
ON U.USER_ID = O.USER_ID 
WHERE GENDER IS NOT NULL
GROUP BY  TO_CHAR(SALES_DATE,'YYYY'), 
          TO_NUMBER(TO_CHAR(SALES_DATE,'MM')), 
          U.GENDER
ORDER BY 1,2,3;


     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     