SELECT  EXTRACT(YEAR FROM SALES_DATE) YEAR,  
        EXTRACT(MONTH FROM SALES_DATE) MONTH, 
        COUNT(DISTINCT O.USER_ID) PURCHASED_USERS,  
        ROUND(COUNT(DISTINCT O.USER_ID) / C.CNT,1) PUCHASED_RATIO
FROM 
    ONLINE_SALE O,
    -- 2021 가입한 유저 ID
    (   SELECT USER_ID 
        FROM USER_INFO  
        WHERE TO_CHAR(JOINED,'YYYY') LIKE '2021%'
    ) U,
    -- 2021 가입한 유저 수
    (
        SELECT COUNT(USER_ID) CNT
        FROM USER_INFO  
        WHERE TO_CHAR(JOINED,'YYYY') LIKE '2021%'
    ) C
WHERE U.USER_ID = O.USER_ID
GROUP BY EXTRACT(YEAR FROM SALES_DATE),  EXTRACT(MONTH FROM SALES_DATE), C.CNT
ORDER BY YEAR, MONTH