SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    (PRICE * SUM(AMOUNT)) AS TOTAL_SALES
FROM 
    FOOD_ORDER O, FOOD_PRODUCT P
WHERE 
    O.PRODUCT_ID = P.PRODUCT_ID
    AND
    DATE_FORMAT(O.PRODUCE_DATE,"%Y-%m") = "2022-05"
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;
    