


SELECT HOUR, COUNT(O.DATETIME) AS COUNT 
FROM
(
    SELECT LEVEL-1 AS HOUR
    FROM DUAL 
    CONNECT BY LEVEL<25
)A 
LEFT JOIN ANIMAL_OUTS O 
ON A.HOUR = TO_NUMBER(TO_CHAR(O.DATETIME,'HH24')) 
GROUP BY HOUR
ORDER BY HOUR; 