-- 코드를 작성해주세요
SELECT 
    YEAR(DIFFERENTIATION_DATE) YEAR, 
    (E.S - SIZE_OF_COLONY) YEAR_DEV, 
    ID
FROM ECOLI_DATA, 
     (SELECT MAX(SIZE_OF_COLONY) S , YEAR(DIFFERENTIATION_DATE) D
      FROM ECOLI_DATA 
      GROUP BY YEAR(DIFFERENTIATION_DATE)) E
WHERE YEAR(DIFFERENTIATION_DATE) = E.D
ORDER BY YEAR, YEAR_DEV

