-- 코드를 작성해주세요
SELECT I2.ID , N.FISH_NAME FISH_NAME, I.LEN LENGTH 
FROM (SELECT FISH_TYPE , MAX(LENGTH) LEN FROM FISH_INFO GROUP BY FISH_TYPE) I, 
     FISH_NAME_INFO N,
     FISH_INFO I2
WHERE N.FISH_TYPE = I.FISH_TYPE AND I2.FISH_TYPE = I.FISH_TYPE AND I2.LENGTH = I.LEN;