-- 코드를 입력하세요
SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F, 
    (SELECT CATEGORY, MAX(PRICE) PRICE
     FROM FOOD_PRODUCT
     GROUP BY CATEGORY HAVING CATEGORY IN ('과자', '국', '김치', '식용유')) GF
WHERE F.CATEGORY IN ('과자', '국', '김치', '식용유') AND
      F.CATEGORY = GF.CATEGORY AND 
      F.PRICE = GF.PRICE
ORDER BY PRICE DESC
    
